Repository googleapis/python-gke-hub, pull requests merged in 2021-04, with the labels that each got.

#9 chore: start tracking obsolete files
  synth.metadata
Labels: api: gkehub, automerge, cla: yes, context: full

#11 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: gkehub, cla: yes, context: full

#10 chore: Migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .pre-commit-config.yaml
  docs/conf.py
  owlbot.py
  synth.metadata
Labels: api: gkehub, automerge, cla: yes

#14 chore: prevent normalization of semver versioning
  setup.py
Labels: api: gkehub, automerge, cla: yes

#19 chore(revert): revert preventing normalization
  setup.py
Labels: api: gkehub, cla: yes
